### PR TITLE
Adds the ability to push new posts onto discussions that aren't public.

### PR DESCRIPTION
**Pull request by luceos**
It's very frustrating having pusher installed, but not seeing new posts pop up on non public
discussions. This PR simply re-uses the existing channels per user by reading
all similar private user channels (which require authentication) and then pushing
the websocket message over the line. This only happens in case the discussion is
not public and it only sends to connected users.

### CODE REVIEW

**Comment by hrvoje-hr** [comment]
@luceos thank you for this! However, I've tested changes on my production forum and couldn't get it to work as described. I'm gonna describe what I did.

1. Replaced codes of both files
2. Restarted Pusher extension
3. Cleared cache

Opened the same discussion in private tag at the same time in two separate sessions with two different accounts. Stream posts don't work.

At the same time, it still works in the environment as described in public discussions.

**Comment by luceos** [comment]
@hrvoje-hr these changes are the raw modifications, you would have to recompile the Javascript so that a new file is generated in js/dist. With prs we're not allowed to commit these dist files as that would complicate merging.

**Comment by luceos** [comment]
@datitisev if you have some time can you do a test run with this code?

**Comment by dsevillamartin** [comment]
@luceos I'll try to do see this weekend.

**Comment by hrvoje-hr** [comment]
@luceos I can help too if you can give me instructions on how to compile and where to place recompiled code.

**Review by askvortsov1 — APPROVED** [review]

**Review by tankerkiller125 — APPROVED** [review]

**Comment by dsevillamartin** [comment]
I've resolved the merge conflict (did it through GitHub, oops merge commit). This code is pretty simple, I think it's fine. I don't know much about Pusher so I won't approve it. But LGTM.

**Review by askvortsov1 — APPROVED** [review]
Confirmed this is still working locally

**Review by tankerkiller125 — APPROVED** [review]

**Comment by askvortsov1** [comment]
Fixes https://github.com/flarum/core/issues/2675

**Pull request merged**
