### PR TITLE
update for mithril 2

### PR DESCRIPTION
**Pull request by askvortsov1**
~~Not tested locally~~

### CODE REVIEW

**Review by franzliedke — APPROVED** [review]
Looks sensible, but needs a manual test, I'd say.

**Review by luceos — APPROVED** [review]
Tested on m2, confirmed it works.

However, flarum/pusher relies on flarum/tags; without tags the pusher extension breaks on posting.. Can we add that dependency?

**Comment by askvortsov1** [comment]
Since that's not a mithril 2 issue, it might be preferable to split that into a separate PR.

**Comment by luceos** [comment]
@askvortsov1 agreed, see #24 (hackish I know and not tested). This one is ready for merging.

**Review by franzliedke — APPROVED** [review]

**Pull request merged**
